name: CI

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
            fontconfig    \
            imagemagick   \
            poppler-utils
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
      - name: Install Tex Live
        run: |
          sudo apt update
          sudo apt install \
            texlive-base              \
            texlive-extra-utils       \
            texlive-fonts-extra       \
            texlive-fonts-recommended \
            texlive-latex-base        \
            texlive-latex-extra       \
            texlive-latex-recommended \
            texlive-xetex
      - name: Build artifacts
        run: |
          # adjust the ImageMagick policies to convert PDF to PNG
          # remove all policies restricting Ghostscript ability to process files
          # https://stackoverflow.com/q/52998331
          # https://stackoverflow.com/a/59193253
          sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
          #
          make -C fonts/
          cp -r fonts/ /usr/share/fonts/
          fc-cache
          make all
      - name: Run checks
        run: |
          make check
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: build
          path: |
            cheatsheets.pdf
            handout-*.pdf
            ./docs/_build/html/
      - uses: actions/upload-artifact@v4
        id: diffs-artifact-upload
        if: ${{ always() }}
        with:
          name: diffs
          path: |
            diffs/
      - name: Output artifacts URL
        run: |
          echo 'Artifact URL:' \
            '${{ steps.diffs-artifact-upload.outputs.artifact-url }}' \
            >> $GITHUB_STEP_SUMMARY
      - name: Publish cheatsheets and handouts
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
          force_orphan: true
